platform :ios, '11.0'

def jigra_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Jigra', :path => '../node_modules/@jigra/ios'
  pod 'JigraCordova', :path => '../node_modules/@jigra/ios'
end

target 'Plugin' do
  jigra_pods
end

target 'PluginTests' do
  jigra_pods
end
