platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def jigra_pods
  # Automatic Jigra Pod dependencies, do not delete
  pod 'Jigra', :path => '../../node_modules/@jigra/ios'
  pod 'JigraCordova', :path => '../../node_modules/@jigra/ios'
  # Do not delete
end

target 'App' do
  jigra_pods
  # Add your Pods here
end
